### PR TITLE
fix(client): Support responses without gzip encoding

### LINKED ISSUE #35: API failures due to quota limits raise confusing errors
If the example code in the README is run using an API key that is out of quota, the error raised from `vt.Client.GetObject` is unhelpful:

```
gzip: invalid header
```

This error is not of type `vt.Error,` so it's not readily captured by client code that is prepared to respond to VT API errors.

### PR DESCRIPTION
**Pull request by mgmacias95**
closes #35

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -167,14 +167,20 @@ func (cli *Client) parseResponse(resp *http.Response) (*Response, error) {
 			resp.Request.Method, resp.Request.URL.String())
 	}
 
-	// Prepare gzip reader for uncompressing gzipped JSON response
-	ungzipper, err := gzip.NewReader(resp.Body)
-	if err != nil {
-		return nil, err
+	var reader io.ReadCloser
+	if strings.Compare(resp.Header.Get("Content-Encoding"), "gzip") == 0 {
```
Comment (lluis-mas) [inline client.go:171]: why not `if resp.Header.Get("Content-Encoding") == "gzip"`

**Review by joseotoro — APPROVED** [review]
